apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      name: logstash
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: logstash
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5044
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/logstash/pipeline
              name: logstash-pipeline
      volumes:
        - name: logstash-pipeline
          configMap:
            name: logstash-config
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: logstash-service
spec:
  selector:
    app: logstash
  ports:
    - port: 5044
      targetPort: 5044
      protocol: TCP
      