apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  # file format
  logstash.conf: |
    input {
      tcp {
        port => 5044
      }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch-service:9200"]
        index => "logs-%{+YYYY.MM.dd}"
      }
    }